name: GHA Release
run-name: Build Test and Release parrot
on: [push]
jobs:
  Build-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Build and Test parrot
        run: |
          echo "Building and Testing parrot for branch: ${{ github.ref }}"
          echo "Build running on a ${{ runner.os }}"
      - name: Check out repository code
        uses: actions/checkout@v6
      - name: List files in the repository
        run: |
          mkdir -p build
          cd build
          cmake ..
          make all
