name: GHA Release
run-name: Build, Test and Release parrot
on: [push]
jobs:
  Build-Test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6
      - name: Build parrot binary
        run: |
          mkdir -p build
          cd build
          cmake ..
          make all
